insert into proyecto (id, code, description, empresa_id) values (452233, 6319, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 936);
insert into proyecto (id, code, description, empresa_id) values (702111, 14351, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 688);
insert into proyecto (id, code, description, empresa_id) values (768468, 47960, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 644);
insert into proyecto (id, code, description, empresa_id) values (322388, 12990, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 94);
insert into proyecto (id, code, description, empresa_id) values (966339, 33601, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 117);
insert into proyecto (id, code, description, empresa_id) values (544115, 39048, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 580);
insert into proyecto (id, code, description, empresa_id) values (387699, 87384, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 516);
insert into proyecto (id, code, description, empresa_id) values (249770, 44753, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 955);
insert into proyecto (id, code, description, empresa_id) values (439597, 35189, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 110);
insert into proyecto (id, code, description, empresa_id) values (952043, 6532, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 470);
insert into proyecto (id, code, description, empresa_id) values (688165, 61701, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 357);
insert into proyecto (id, code, description, empresa_id) values (563754, 48473, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 757);
insert into proyecto (id, code, description, empresa_id) values (90919, 96087, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 977);
insert into proyecto (id, code, description, empresa_id) values (851890, 92225, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 61);
insert into proyecto (id, code, description, empresa_id) values (619586, 11616, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 700);
insert into proyecto (id, code, description, empresa_id) values (279351, 20161, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 129);
insert into proyecto (id, code, description, empresa_id) values (263302, 16968, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 507);
insert into proyecto (id, code, description, empresa_id) values (211239, 43139, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 34);
insert into proyecto (id, code, description, empresa_id) values (115645, 44529, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 72);
insert into proyecto (id, code, description, empresa_id) values (500886, 47883, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 181);
insert into proyecto (id, code, description, empresa_id) values (223627, 61869, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 300);
insert into proyecto (id, code, description, empresa_id) values (226759, 50604, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 936);
insert into proyecto (id, code, description, empresa_id) values (647945, 64691, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 489);
insert into proyecto (id, code, description, empresa_id) values (330843, 45291, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 73);
insert into proyecto (id, code, description, empresa_id) values (57011, 30608, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 916);
insert into proyecto (id, code, description, empresa_id) values (807786, 40106, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 393);
insert into proyecto (id, code, description, empresa_id) values (191120, 99996, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 268);
insert into proyecto (id, code, description, empresa_id) values (455200, 45464, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 185);
insert into proyecto (id, code, description, empresa_id) values (415268, 7580, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 708);
insert into proyecto (id, code, description, empresa_id) values (129948, 26801, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 206);
insert into proyecto (id, code, description, empresa_id) values (13868, 29810, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 308);
insert into proyecto (id, code, description, empresa_id) values (671486, 21217, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 620);
insert into proyecto (id, code, description, empresa_id) values (555005, 50421, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 967);
insert into proyecto (id, code, description, empresa_id) values (235987, 23279, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 902);
insert into proyecto (id, code, description, empresa_id) values (198751, 77921, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 618);
insert into proyecto (id, code, description, empresa_id) values (313994, 33362, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 281);
insert into proyecto (id, code, description, empresa_id) values (778904, 38273, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 500);
insert into proyecto (id, code, description, empresa_id) values (938251, 47734, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 994);
insert into proyecto (id, code, description, empresa_id) values (453136, 97135, 'Proyecto de granallado para restauración del exterior del edificio municipal', 723);
insert into proyecto (id, code, description, empresa_id) values (670087, 85223, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 534);
insert into proyecto (id, code, description, empresa_id) values (182862, 58482, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 876);
insert into proyecto (id, code, description, empresa_id) values (895389, 14238, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 317);
insert into proyecto (id, code, description, empresa_id) values (182087, 25784, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 23);
insert into proyecto (id, code, description, empresa_id) values (960928, 93668, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 542);
insert into proyecto (id, code, description, empresa_id) values (9861, 61533, 'Proyecto de granallado para restauración del exterior del edificio municipal', 688);
insert into proyecto (id, code, description, empresa_id) values (538212, 76970, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 115);
insert into proyecto (id, code, description, empresa_id) values (100357, 34825, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 236);
insert into proyecto (id, code, description, empresa_id) values (601810, 43394, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 821);
insert into proyecto (id, code, description, empresa_id) values (8670, 85439, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 331);
insert into proyecto (id, code, description, empresa_id) values (624526, 11540, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 719);
insert into proyecto (id, code, description, empresa_id) values (132432, 67653, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 396);
insert into proyecto (id, code, description, empresa_id) values (397409, 87763, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 71);
insert into proyecto (id, code, description, empresa_id) values (177347, 44901, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 164);
insert into proyecto (id, code, description, empresa_id) values (566007, 62871, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 555);
insert into proyecto (id, code, description, empresa_id) values (784451, 23061, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 151);
insert into proyecto (id, code, description, empresa_id) values (956135, 57585, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 258);
insert into proyecto (id, code, description, empresa_id) values (87177, 86167, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 132);
insert into proyecto (id, code, description, empresa_id) values (351323, 7575, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 203);
insert into proyecto (id, code, description, empresa_id) values (55669, 25445, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 274);
insert into proyecto (id, code, description, empresa_id) values (883424, 22941, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 628);
insert into proyecto (id, code, description, empresa_id) values (514489, 17482, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 192);
insert into proyecto (id, code, description, empresa_id) values (699031, 73356, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 692);
insert into proyecto (id, code, description, empresa_id) values (785902, 3877, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 891);
insert into proyecto (id, code, description, empresa_id) values (868611, 71263, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 176);
insert into proyecto (id, code, description, empresa_id) values (667814, 79754, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 715);
insert into proyecto (id, code, description, empresa_id) values (989154, 1851, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 226);
insert into proyecto (id, code, description, empresa_id) values (110901, 28551, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 261);
insert into proyecto (id, code, description, empresa_id) values (790323, 29942, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 830);
insert into proyecto (id, code, description, empresa_id) values (997920, 92962, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 937);
insert into proyecto (id, code, description, empresa_id) values (709797, 27936, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 421);
insert into proyecto (id, code, description, empresa_id) values (689235, 56561, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 209);
insert into proyecto (id, code, description, empresa_id) values (289241, 28511, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 453);
insert into proyecto (id, code, description, empresa_id) values (473065, 66708, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 786);
insert into proyecto (id, code, description, empresa_id) values (118505, 82228, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 827);
insert into proyecto (id, code, description, empresa_id) values (221208, 1929, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 936);
insert into proyecto (id, code, description, empresa_id) values (998753, 47061, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 967);
insert into proyecto (id, code, description, empresa_id) values (649074, 20809, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 640);
insert into proyecto (id, code, description, empresa_id) values (136159, 38977, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 657);
insert into proyecto (id, code, description, empresa_id) values (617663, 79825, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 136);
insert into proyecto (id, code, description, empresa_id) values (495636, 73875, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 889);
insert into proyecto (id, code, description, empresa_id) values (733142, 70412, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 109);
insert into proyecto (id, code, description, empresa_id) values (831234, 28715, 'Proyecto de granallado para restauración del exterior del edificio municipal', 502);
insert into proyecto (id, code, description, empresa_id) values (80781, 34240, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 882);
insert into proyecto (id, code, description, empresa_id) values (63560, 95309, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 459);
insert into proyecto (id, code, description, empresa_id) values (663612, 49388, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 769);
insert into proyecto (id, code, description, empresa_id) values (466317, 88896, 'Proyecto de granallado para restauración del exterior del edificio municipal', 935);
insert into proyecto (id, code, description, empresa_id) values (946808, 14695, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 508);
insert into proyecto (id, code, description, empresa_id) values (804294, 60508, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 655);
insert into proyecto (id, code, description, empresa_id) values (469844, 80786, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 497);
insert into proyecto (id, code, description, empresa_id) values (232689, 65838, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 502);
insert into proyecto (id, code, description, empresa_id) values (904537, 4573, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 487);
insert into proyecto (id, code, description, empresa_id) values (824394, 31645, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 273);
insert into proyecto (id, code, description, empresa_id) values (106708, 16744, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 542);
insert into proyecto (id, code, description, empresa_id) values (470162, 23872, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 759);
insert into proyecto (id, code, description, empresa_id) values (300518, 5935, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 118);
insert into proyecto (id, code, description, empresa_id) values (317386, 53326, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 514);
insert into proyecto (id, code, description, empresa_id) values (915182, 89679, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 235);
insert into proyecto (id, code, description, empresa_id) values (681816, 53844, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 407);
insert into proyecto (id, code, description, empresa_id) values (276742, 55266, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 370);
insert into proyecto (id, code, description, empresa_id) values (529111, 10696, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 552);
insert into proyecto (id, code, description, empresa_id) values (473198, 9095, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 74);
insert into proyecto (id, code, description, empresa_id) values (523531, 58186, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 190);
insert into proyecto (id, code, description, empresa_id) values (426922, 30723, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 842);
insert into proyecto (id, code, description, empresa_id) values (762240, 17832, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 449);
insert into proyecto (id, code, description, empresa_id) values (865982, 73992, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 714);
insert into proyecto (id, code, description, empresa_id) values (2325, 99357, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 724);
insert into proyecto (id, code, description, empresa_id) values (441727, 66921, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 220);
insert into proyecto (id, code, description, empresa_id) values (210338, 14296, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 11);
insert into proyecto (id, code, description, empresa_id) values (317432, 14099, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 508);
insert into proyecto (id, code, description, empresa_id) values (58323, 71714, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 268);
insert into proyecto (id, code, description, empresa_id) values (699793, 37314, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 62);
insert into proyecto (id, code, description, empresa_id) values (601033, 27492, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 658);
insert into proyecto (id, code, description, empresa_id) values (90871, 25371, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 813);
insert into proyecto (id, code, description, empresa_id) values (169015, 15594, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 490);
insert into proyecto (id, code, description, empresa_id) values (333674, 68168, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 291);
insert into proyecto (id, code, description, empresa_id) values (221025, 19462, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 132);
insert into proyecto (id, code, description, empresa_id) values (363590, 53778, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 144);
insert into proyecto (id, code, description, empresa_id) values (881674, 27608, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 339);
insert into proyecto (id, code, description, empresa_id) values (58077, 9553, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 309);
insert into proyecto (id, code, description, empresa_id) values (602171, 92545, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 43);
insert into proyecto (id, code, description, empresa_id) values (171536, 37119, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 225);
insert into proyecto (id, code, description, empresa_id) values (404899, 40715, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 699);
insert into proyecto (id, code, description, empresa_id) values (489803, 2592, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 228);
insert into proyecto (id, code, description, empresa_id) values (652705, 13086, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 330);
insert into proyecto (id, code, description, empresa_id) values (403058, 95642, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 130);
insert into proyecto (id, code, description, empresa_id) values (980958, 95663, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 755);
insert into proyecto (id, code, description, empresa_id) values (95347, 78087, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 499);
insert into proyecto (id, code, description, empresa_id) values (812575, 34478, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 320);
insert into proyecto (id, code, description, empresa_id) values (586545, 92960, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 836);
insert into proyecto (id, code, description, empresa_id) values (878961, 95764, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 252);
insert into proyecto (id, code, description, empresa_id) values (84395, 18797, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 946);
insert into proyecto (id, code, description, empresa_id) values (775977, 90655, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 334);
insert into proyecto (id, code, description, empresa_id) values (853556, 31727, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 979);
insert into proyecto (id, code, description, empresa_id) values (693689, 8225, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 92);
insert into proyecto (id, code, description, empresa_id) values (52826, 97382, 'Proyecto de granallado para restauración del exterior del edificio municipal', 481);
insert into proyecto (id, code, description, empresa_id) values (344237, 76222, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 556);
insert into proyecto (id, code, description, empresa_id) values (128066, 38769, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 706);
insert into proyecto (id, code, description, empresa_id) values (79429, 91737, 'Proyecto de granallado para restauración del exterior del edificio municipal', 265);
insert into proyecto (id, code, description, empresa_id) values (577601, 89158, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 957);
insert into proyecto (id, code, description, empresa_id) values (455677, 91407, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 701);
insert into proyecto (id, code, description, empresa_id) values (592304, 51841, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 903);
insert into proyecto (id, code, description, empresa_id) values (558975, 33174, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 388);
insert into proyecto (id, code, description, empresa_id) values (427917, 34892, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 477);
insert into proyecto (id, code, description, empresa_id) values (964267, 24777, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 951);
insert into proyecto (id, code, description, empresa_id) values (47678, 86461, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 34);
insert into proyecto (id, code, description, empresa_id) values (291405, 89514, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 393);
insert into proyecto (id, code, description, empresa_id) values (116265, 98369, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 277);
insert into proyecto (id, code, description, empresa_id) values (454403, 15032, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 784);
insert into proyecto (id, code, description, empresa_id) values (635852, 94724, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 417);
insert into proyecto (id, code, description, empresa_id) values (117648, 18658, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 196);
insert into proyecto (id, code, description, empresa_id) values (467205, 37467, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 135);
insert into proyecto (id, code, description, empresa_id) values (558391, 13183, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 162);
insert into proyecto (id, code, description, empresa_id) values (424168, 3362, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 713);
insert into proyecto (id, code, description, empresa_id) values (863379, 28370, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 727);
insert into proyecto (id, code, description, empresa_id) values (915321, 43171, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 512);
insert into proyecto (id, code, description, empresa_id) values (151072, 89498, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 537);
insert into proyecto (id, code, description, empresa_id) values (74143, 64608, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 92);
insert into proyecto (id, code, description, empresa_id) values (797191, 99677, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 592);
insert into proyecto (id, code, description, empresa_id) values (257682, 35089, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 814);
insert into proyecto (id, code, description, empresa_id) values (975479, 19683, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 797);
insert into proyecto (id, code, description, empresa_id) values (51248, 52330, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 620);
insert into proyecto (id, code, description, empresa_id) values (410322, 34832, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 204);
insert into proyecto (id, code, description, empresa_id) values (781096, 48627, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 821);
insert into proyecto (id, code, description, empresa_id) values (904631, 99910, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 60);
insert into proyecto (id, code, description, empresa_id) values (473500, 28244, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 306);
insert into proyecto (id, code, description, empresa_id) values (694574, 11799, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 775);
insert into proyecto (id, code, description, empresa_id) values (556476, 63105, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 163);
insert into proyecto (id, code, description, empresa_id) values (717084, 39146, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 115);
insert into proyecto (id, code, description, empresa_id) values (571016, 5704, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 975);
insert into proyecto (id, code, description, empresa_id) values (906799, 50536, 'Proyecto de granallado para restauración del exterior del edificio municipal', 724);
insert into proyecto (id, code, description, empresa_id) values (633177, 13642, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 74);
insert into proyecto (id, code, description, empresa_id) values (608310, 86946, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 573);
insert into proyecto (id, code, description, empresa_id) values (20974, 57903, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 663);
insert into proyecto (id, code, description, empresa_id) values (205424, 72216, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 851);
insert into proyecto (id, code, description, empresa_id) values (986821, 4999, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 944);
insert into proyecto (id, code, description, empresa_id) values (202596, 80310, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 323);
insert into proyecto (id, code, description, empresa_id) values (23072, 40071, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 792);
insert into proyecto (id, code, description, empresa_id) values (717796, 40856, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 460);
insert into proyecto (id, code, description, empresa_id) values (41, 96903, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 677);
insert into proyecto (id, code, description, empresa_id) values (751236, 18558, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 288);
insert into proyecto (id, code, description, empresa_id) values (871595, 76619, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 76);
insert into proyecto (id, code, description, empresa_id) values (29327, 30943, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 575);
insert into proyecto (id, code, description, empresa_id) values (441444, 26444, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 492);
insert into proyecto (id, code, description, empresa_id) values (995945, 2833, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 669);
insert into proyecto (id, code, description, empresa_id) values (51741, 65649, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 452);
insert into proyecto (id, code, description, empresa_id) values (830289, 37114, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 263);
insert into proyecto (id, code, description, empresa_id) values (60417, 94611, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 258);
insert into proyecto (id, code, description, empresa_id) values (978657, 57005, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 257);
insert into proyecto (id, code, description, empresa_id) values (124354, 33982, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 612);
insert into proyecto (id, code, description, empresa_id) values (980572, 26077, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 628);
insert into proyecto (id, code, description, empresa_id) values (801834, 8021, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 305);
insert into proyecto (id, code, description, empresa_id) values (284460, 38534, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 804);
insert into proyecto (id, code, description, empresa_id) values (82043, 63678, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 750);
insert into proyecto (id, code, description, empresa_id) values (844742, 56031, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 979);
insert into proyecto (id, code, description, empresa_id) values (229010, 31638, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 192);
insert into proyecto (id, code, description, empresa_id) values (416592, 54928, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 762);
insert into proyecto (id, code, description, empresa_id) values (76966, 46321, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 447);
insert into proyecto (id, code, description, empresa_id) values (443169, 89549, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 176);
insert into proyecto (id, code, description, empresa_id) values (175076, 90654, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 353);
insert into proyecto (id, code, description, empresa_id) values (781321, 61891, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 122);
insert into proyecto (id, code, description, empresa_id) values (642759, 90501, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 138);
insert into proyecto (id, code, description, empresa_id) values (566235, 70325, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 215);
insert into proyecto (id, code, description, empresa_id) values (289633, 83731, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 983);
insert into proyecto (id, code, description, empresa_id) values (152104, 99588, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 66);
insert into proyecto (id, code, description, empresa_id) values (871952, 15246, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 174);
insert into proyecto (id, code, description, empresa_id) values (896928, 90795, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 177);
insert into proyecto (id, code, description, empresa_id) values (178451, 52742, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 741);
insert into proyecto (id, code, description, empresa_id) values (758465, 89950, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 247);
insert into proyecto (id, code, description, empresa_id) values (306252, 51460, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 405);
insert into proyecto (id, code, description, empresa_id) values (764054, 20013, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 225);
insert into proyecto (id, code, description, empresa_id) values (630656, 60761, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 7);
insert into proyecto (id, code, description, empresa_id) values (376877, 66311, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 243);
insert into proyecto (id, code, description, empresa_id) values (558939, 94501, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 110);
insert into proyecto (id, code, description, empresa_id) values (851792, 7008, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 383);
insert into proyecto (id, code, description, empresa_id) values (983125, 15103, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 80);
insert into proyecto (id, code, description, empresa_id) values (728229, 81151, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 236);
insert into proyecto (id, code, description, empresa_id) values (229462, 31594, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 574);
insert into proyecto (id, code, description, empresa_id) values (231744, 29812, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 853);
insert into proyecto (id, code, description, empresa_id) values (76010, 10389, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 523);
insert into proyecto (id, code, description, empresa_id) values (790569, 87199, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 144);
insert into proyecto (id, code, description, empresa_id) values (187871, 87628, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 99);
insert into proyecto (id, code, description, empresa_id) values (365869, 59150, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 96);
insert into proyecto (id, code, description, empresa_id) values (31683, 88837, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 186);
insert into proyecto (id, code, description, empresa_id) values (376975, 13040, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 759);
insert into proyecto (id, code, description, empresa_id) values (471788, 14210, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 318);
insert into proyecto (id, code, description, empresa_id) values (93041, 45003, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 694);
insert into proyecto (id, code, description, empresa_id) values (433307, 63166, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 812);
insert into proyecto (id, code, description, empresa_id) values (389595, 87885, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 927);
insert into proyecto (id, code, description, empresa_id) values (175428, 36212, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 29);
insert into proyecto (id, code, description, empresa_id) values (736536, 23048, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 884);
insert into proyecto (id, code, description, empresa_id) values (696714, 77962, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 486);
insert into proyecto (id, code, description, empresa_id) values (74166, 57156, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 822);
insert into proyecto (id, code, description, empresa_id) values (394254, 46329, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 63);
insert into proyecto (id, code, description, empresa_id) values (32616, 54517, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 843);
insert into proyecto (id, code, description, empresa_id) values (881923, 2009, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 704);
insert into proyecto (id, code, description, empresa_id) values (290269, 61519, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 212);
insert into proyecto (id, code, description, empresa_id) values (93731, 5993, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 327);
insert into proyecto (id, code, description, empresa_id) values (370263, 92267, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 151);
insert into proyecto (id, code, description, empresa_id) values (889759, 76752, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 367);
insert into proyecto (id, code, description, empresa_id) values (178013, 40787, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 362);
insert into proyecto (id, code, description, empresa_id) values (298315, 84298, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 793);
insert into proyecto (id, code, description, empresa_id) values (93504, 26614, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 699);
insert into proyecto (id, code, description, empresa_id) values (295132, 90952, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 907);
insert into proyecto (id, code, description, empresa_id) values (47598, 66544, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 61);
insert into proyecto (id, code, description, empresa_id) values (484526, 19386, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 536);
insert into proyecto (id, code, description, empresa_id) values (942103, 51913, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 321);
insert into proyecto (id, code, description, empresa_id) values (774470, 65870, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 657);
insert into proyecto (id, code, description, empresa_id) values (148092, 15569, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 948);
insert into proyecto (id, code, description, empresa_id) values (167608, 58842, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 91);
insert into proyecto (id, code, description, empresa_id) values (736397, 25055, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 262);
insert into proyecto (id, code, description, empresa_id) values (79090, 2300, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 438);
insert into proyecto (id, code, description, empresa_id) values (681899, 42999, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 74);
insert into proyecto (id, code, description, empresa_id) values (140789, 39830, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 364);
insert into proyecto (id, code, description, empresa_id) values (152752, 65345, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 925);
insert into proyecto (id, code, description, empresa_id) values (468351, 76842, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 883);
insert into proyecto (id, code, description, empresa_id) values (554708, 79903, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 102);
insert into proyecto (id, code, description, empresa_id) values (542050, 19590, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 245);
insert into proyecto (id, code, description, empresa_id) values (137235, 33700, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 291);
insert into proyecto (id, code, description, empresa_id) values (759651, 98131, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 775);
insert into proyecto (id, code, description, empresa_id) values (565329, 61764, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 683);
insert into proyecto (id, code, description, empresa_id) values (939985, 20914, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 347);
insert into proyecto (id, code, description, empresa_id) values (553166, 55681, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 677);
insert into proyecto (id, code, description, empresa_id) values (123833, 75570, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 734);
insert into proyecto (id, code, description, empresa_id) values (289879, 6894, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 15);
insert into proyecto (id, code, description, empresa_id) values (653883, 58857, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 843);
insert into proyecto (id, code, description, empresa_id) values (544787, 32249, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 424);
insert into proyecto (id, code, description, empresa_id) values (556511, 13608, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 928);
insert into proyecto (id, code, description, empresa_id) values (952248, 1916, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 170);
insert into proyecto (id, code, description, empresa_id) values (836638, 38203, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 646);
insert into proyecto (id, code, description, empresa_id) values (388757, 66338, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 641);
insert into proyecto (id, code, description, empresa_id) values (988360, 41934, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 877);
insert into proyecto (id, code, description, empresa_id) values (903143, 5130, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 467);
insert into proyecto (id, code, description, empresa_id) values (26454, 76998, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 42);
insert into proyecto (id, code, description, empresa_id) values (436170, 84068, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 269);
insert into proyecto (id, code, description, empresa_id) values (961422, 96823, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 956);
insert into proyecto (id, code, description, empresa_id) values (543654, 23903, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 426);
insert into proyecto (id, code, description, empresa_id) values (753954, 61919, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 955);
insert into proyecto (id, code, description, empresa_id) values (460732, 63047, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 187);
insert into proyecto (id, code, description, empresa_id) values (968723, 76946, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 979);
insert into proyecto (id, code, description, empresa_id) values (104695, 68699, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 45);
insert into proyecto (id, code, description, empresa_id) values (166849, 26930, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 867);
insert into proyecto (id, code, description, empresa_id) values (835916, 38915, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 260);
insert into proyecto (id, code, description, empresa_id) values (904473, 1714, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 272);
insert into proyecto (id, code, description, empresa_id) values (160559, 93074, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 393);
insert into proyecto (id, code, description, empresa_id) values (231833, 49117, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 476);
insert into proyecto (id, code, description, empresa_id) values (518222, 88981, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 582);
insert into proyecto (id, code, description, empresa_id) values (867824, 83016, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 427);
insert into proyecto (id, code, description, empresa_id) values (673625, 41663, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 978);
insert into proyecto (id, code, description, empresa_id) values (291201, 44857, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 590);
insert into proyecto (id, code, description, empresa_id) values (690057, 8744, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 736);
insert into proyecto (id, code, description, empresa_id) values (992672, 40567, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 478);
insert into proyecto (id, code, description, empresa_id) values (747880, 96595, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 541);
insert into proyecto (id, code, description, empresa_id) values (468500, 40899, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 480);
insert into proyecto (id, code, description, empresa_id) values (442748, 37287, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 839);
insert into proyecto (id, code, description, empresa_id) values (494358, 8512, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 999);
insert into proyecto (id, code, description, empresa_id) values (403604, 7283, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 461);
insert into proyecto (id, code, description, empresa_id) values (449949, 17719, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 92);
insert into proyecto (id, code, description, empresa_id) values (653722, 30491, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 484);
insert into proyecto (id, code, description, empresa_id) values (93139, 59057, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 899);
insert into proyecto (id, code, description, empresa_id) values (348432, 79091, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 392);
insert into proyecto (id, code, description, empresa_id) values (592154, 70799, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 780);
insert into proyecto (id, code, description, empresa_id) values (574410, 53051, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 341);
insert into proyecto (id, code, description, empresa_id) values (910710, 28046, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 482);
insert into proyecto (id, code, description, empresa_id) values (667316, 20599, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 475);
insert into proyecto (id, code, description, empresa_id) values (123750, 62668, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 999);
insert into proyecto (id, code, description, empresa_id) values (528575, 81205, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 573);
insert into proyecto (id, code, description, empresa_id) values (71173, 22429, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 426);
insert into proyecto (id, code, description, empresa_id) values (147452, 2975, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 362);
insert into proyecto (id, code, description, empresa_id) values (476812, 56537, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 336);
insert into proyecto (id, code, description, empresa_id) values (477172, 96728, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 547);
insert into proyecto (id, code, description, empresa_id) values (62810, 56882, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 601);
insert into proyecto (id, code, description, empresa_id) values (134840, 63522, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 449);
insert into proyecto (id, code, description, empresa_id) values (796964, 41580, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 999);
insert into proyecto (id, code, description, empresa_id) values (24469, 63980, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 468);
insert into proyecto (id, code, description, empresa_id) values (554692, 50800, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 476);
insert into proyecto (id, code, description, empresa_id) values (953291, 80181, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 268);
insert into proyecto (id, code, description, empresa_id) values (459913, 51852, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 767);
insert into proyecto (id, code, description, empresa_id) values (416695, 44777, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 229);
insert into proyecto (id, code, description, empresa_id) values (268912, 98313, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 755);
insert into proyecto (id, code, description, empresa_id) values (86325, 93816, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 224);
insert into proyecto (id, code, description, empresa_id) values (114445, 6200, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 907);
insert into proyecto (id, code, description, empresa_id) values (992091, 32165, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 866);
insert into proyecto (id, code, description, empresa_id) values (78042, 68305, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 129);
insert into proyecto (id, code, description, empresa_id) values (629315, 28466, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 177);
insert into proyecto (id, code, description, empresa_id) values (719397, 17115, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 133);
insert into proyecto (id, code, description, empresa_id) values (10911, 71652, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 302);
insert into proyecto (id, code, description, empresa_id) values (100594, 45721, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 213);
insert into proyecto (id, code, description, empresa_id) values (650295, 9461, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 329);
insert into proyecto (id, code, description, empresa_id) values (282806, 75203, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 745);
insert into proyecto (id, code, description, empresa_id) values (837119, 32126, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 568);
insert into proyecto (id, code, description, empresa_id) values (826368, 43102, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 297);
insert into proyecto (id, code, description, empresa_id) values (850195, 64482, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 498);
insert into proyecto (id, code, description, empresa_id) values (863435, 50345, 'Proyecto de granallado para restauración del exterior del edificio municipal', 138);
insert into proyecto (id, code, description, empresa_id) values (206023, 6449, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 320);
insert into proyecto (id, code, description, empresa_id) values (776724, 43148, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 357);
insert into proyecto (id, code, description, empresa_id) values (280790, 89529, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 988);
insert into proyecto (id, code, description, empresa_id) values (945322, 19593, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 397);
insert into proyecto (id, code, description, empresa_id) values (38070, 7208, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 904);
insert into proyecto (id, code, description, empresa_id) values (178800, 50921, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 236);
insert into proyecto (id, code, description, empresa_id) values (663894, 62314, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 714);
insert into proyecto (id, code, description, empresa_id) values (185576, 26610, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 648);
insert into proyecto (id, code, description, empresa_id) values (498633, 78718, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 590);
insert into proyecto (id, code, description, empresa_id) values (353247, 39290, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 816);
insert into proyecto (id, code, description, empresa_id) values (572800, 37787, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 87);
insert into proyecto (id, code, description, empresa_id) values (981907, 15200, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 638);
insert into proyecto (id, code, description, empresa_id) values (350778, 66767, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 664);
insert into proyecto (id, code, description, empresa_id) values (852126, 68298, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 163);
insert into proyecto (id, code, description, empresa_id) values (490775, 2076, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 772);
insert into proyecto (id, code, description, empresa_id) values (41579, 2116, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 242);
insert into proyecto (id, code, description, empresa_id) values (236817, 89078, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 926);
insert into proyecto (id, code, description, empresa_id) values (479686, 2318, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 672);
insert into proyecto (id, code, description, empresa_id) values (762078, 79294, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 665);
insert into proyecto (id, code, description, empresa_id) values (351987, 80908, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 134);
insert into proyecto (id, code, description, empresa_id) values (888808, 39636, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 311);
insert into proyecto (id, code, description, empresa_id) values (308745, 52132, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 695);
insert into proyecto (id, code, description, empresa_id) values (703910, 99393, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 967);
insert into proyecto (id, code, description, empresa_id) values (686712, 17553, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 23);
insert into proyecto (id, code, description, empresa_id) values (98338, 18201, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 789);
insert into proyecto (id, code, description, empresa_id) values (321342, 25785, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 985);
insert into proyecto (id, code, description, empresa_id) values (717090, 73045, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 800);
insert into proyecto (id, code, description, empresa_id) values (385380, 24660, 'Proyecto de granallado para restauración del exterior del edificio municipal', 442);
insert into proyecto (id, code, description, empresa_id) values (616195, 5759, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 568);
insert into proyecto (id, code, description, empresa_id) values (770772, 15071, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 129);
insert into proyecto (id, code, description, empresa_id) values (736017, 44085, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 307);
insert into proyecto (id, code, description, empresa_id) values (671429, 86527, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 610);
insert into proyecto (id, code, description, empresa_id) values (248491, 14718, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 108);
insert into proyecto (id, code, description, empresa_id) values (401652, 11666, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 420);
insert into proyecto (id, code, description, empresa_id) values (547185, 49821, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 944);
insert into proyecto (id, code, description, empresa_id) values (471660, 91247, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 882);
insert into proyecto (id, code, description, empresa_id) values (779061, 48050, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 924);
insert into proyecto (id, code, description, empresa_id) values (650290, 54540, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 317);
insert into proyecto (id, code, description, empresa_id) values (145095, 66587, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 407);
insert into proyecto (id, code, description, empresa_id) values (300805, 51507, 'Proyecto de granallado para restauración del exterior del edificio municipal', 190);
insert into proyecto (id, code, description, empresa_id) values (95342, 65305, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 882);
insert into proyecto (id, code, description, empresa_id) values (223760, 68116, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 235);
insert into proyecto (id, code, description, empresa_id) values (556758, 74491, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 923);
insert into proyecto (id, code, description, empresa_id) values (27933, 48078, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 768);
insert into proyecto (id, code, description, empresa_id) values (544778, 67832, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 117);
insert into proyecto (id, code, description, empresa_id) values (700594, 86346, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 5);
insert into proyecto (id, code, description, empresa_id) values (362704, 3212, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 377);
insert into proyecto (id, code, description, empresa_id) values (545329, 31585, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 683);
insert into proyecto (id, code, description, empresa_id) values (170214, 67216, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 44);
insert into proyecto (id, code, description, empresa_id) values (885191, 96064, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 259);
insert into proyecto (id, code, description, empresa_id) values (817269, 14635, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 149);
insert into proyecto (id, code, description, empresa_id) values (558872, 4631, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 923);
insert into proyecto (id, code, description, empresa_id) values (714565, 69276, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 217);
insert into proyecto (id, code, description, empresa_id) values (703927, 35165, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 432);
insert into proyecto (id, code, description, empresa_id) values (701777, 9808, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 634);
insert into proyecto (id, code, description, empresa_id) values (848113, 85340, 'Renovación y ensanchamiento de vereda en el lado sur de la avenida para mejorar la accesibilidad', 544);
insert into proyecto (id, code, description, empresa_id) values (332193, 65009, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 924);
insert into proyecto (id, code, description, empresa_id) values (312178, 51747, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 538);
insert into proyecto (id, code, description, empresa_id) values (721782, 4102, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 307);
insert into proyecto (id, code, description, empresa_id) values (410043, 4247, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 30);
insert into proyecto (id, code, description, empresa_id) values (546516, 11642, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 459);
insert into proyecto (id, code, description, empresa_id) values (900961, 6954, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 54);
insert into proyecto (id, code, description, empresa_id) values (181180, 12892, 'Proyecto de granallado para restauración del exterior del edificio municipal', 172);
insert into proyecto (id, code, description, empresa_id) values (486843, 15647, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 970);
insert into proyecto (id, code, description, empresa_id) values (293439, 14569, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 761);
insert into proyecto (id, code, description, empresa_id) values (745453, 42511, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 148);
insert into proyecto (id, code, description, empresa_id) values (455389, 23882, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 744);
insert into proyecto (id, code, description, empresa_id) values (52558, 9962, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 497);
insert into proyecto (id, code, description, empresa_id) values (263874, 59571, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 318);
insert into proyecto (id, code, description, empresa_id) values (300757, 78762, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 192);
insert into proyecto (id, code, description, empresa_id) values (537114, 9532, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 729);
insert into proyecto (id, code, description, empresa_id) values (768348, 47760, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 315);
insert into proyecto (id, code, description, empresa_id) values (439344, 77108, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 732);
insert into proyecto (id, code, description, empresa_id) values (622691, 34218, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 991);
insert into proyecto (id, code, description, empresa_id) values (504882, 10936, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 795);
insert into proyecto (id, code, description, empresa_id) values (593460, 98542, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 161);
insert into proyecto (id, code, description, empresa_id) values (107356, 74144, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 961);
insert into proyecto (id, code, description, empresa_id) values (644487, 66732, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 554);
insert into proyecto (id, code, description, empresa_id) values (608866, 17056, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 340);
insert into proyecto (id, code, description, empresa_id) values (137490, 78134, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 246);
insert into proyecto (id, code, description, empresa_id) values (588200, 79517, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 301);
insert into proyecto (id, code, description, empresa_id) values (679032, 92562, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 318);
insert into proyecto (id, code, description, empresa_id) values (58084, 28431, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 857);
insert into proyecto (id, code, description, empresa_id) values (833243, 3962, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 451);
insert into proyecto (id, code, description, empresa_id) values (35560, 77076, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 599);
insert into proyecto (id, code, description, empresa_id) values (916353, 73080, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 832);
insert into proyecto (id, code, description, empresa_id) values (337942, 74546, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 135);
insert into proyecto (id, code, description, empresa_id) values (394944, 2274, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 780);
insert into proyecto (id, code, description, empresa_id) values (312345, 78546, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 308);
insert into proyecto (id, code, description, empresa_id) values (335736, 60758, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 905);
insert into proyecto (id, code, description, empresa_id) values (712519, 84744, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 773);
insert into proyecto (id, code, description, empresa_id) values (293480, 45648, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 127);
insert into proyecto (id, code, description, empresa_id) values (495464, 57353, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 127);
insert into proyecto (id, code, description, empresa_id) values (184564, 40480, 'Montaje de galpón prefabricado en el sector norte del terreno para almacenamiento de maquinaria', 425);
insert into proyecto (id, code, description, empresa_id) values (515172, 1356, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 589);
insert into proyecto (id, code, description, empresa_id) values (631927, 42515, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 954);
insert into proyecto (id, code, description, empresa_id) values (551283, 3231, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 79);
insert into proyecto (id, code, description, empresa_id) values (842288, 81414, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 64);
insert into proyecto (id, code, description, empresa_id) values (814562, 16810, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 584);
insert into proyecto (id, code, description, empresa_id) values (764993, 92588, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 280);
insert into proyecto (id, code, description, empresa_id) values (952529, 62841, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 809);
insert into proyecto (id, code, description, empresa_id) values (284755, 96639, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 68);
insert into proyecto (id, code, description, empresa_id) values (634622, 71707, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 866);
insert into proyecto (id, code, description, empresa_id) values (574787, 62843, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 536);
insert into proyecto (id, code, description, empresa_id) values (483896, 92872, 'Tratamiento de granallado y aplicación de pintura intumescente en el edificio municipal para protección contra incendios', 621);
insert into proyecto (id, code, description, empresa_id) values (328497, 12911, 'Proyecto de granallado para restauración del exterior del edificio municipal', 379);
insert into proyecto (id, code, description, empresa_id) values (160706, 95353, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 166);
insert into proyecto (id, code, description, empresa_id) values (431287, 7993, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 144);
insert into proyecto (id, code, description, empresa_id) values (250110, 78394, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 390);
insert into proyecto (id, code, description, empresa_id) values (903853, 90680, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 675);
insert into proyecto (id, code, description, empresa_id) values (477267, 22479, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 242);
insert into proyecto (id, code, description, empresa_id) values (253038, 39457, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 234);
insert into proyecto (id, code, description, empresa_id) values (868166, 89786, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 875);
insert into proyecto (id, code, description, empresa_id) values (69287, 53873, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 969);
insert into proyecto (id, code, description, empresa_id) values (572330, 88555, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 645);
insert into proyecto (id, code, description, empresa_id) values (997902, 18116, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 633);
insert into proyecto (id, code, description, empresa_id) values (795743, 79874, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 936);
insert into proyecto (id, code, description, empresa_id) values (247376, 15645, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 577);
insert into proyecto (id, code, description, empresa_id) values (106987, 50474, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 900);
insert into proyecto (id, code, description, empresa_id) values (476142, 49558, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 86);
insert into proyecto (id, code, description, empresa_id) values (260763, 99843, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 504);
insert into proyecto (id, code, description, empresa_id) values (372346, 71103, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 692);
insert into proyecto (id, code, description, empresa_id) values (927783, 80847, 'Diseño y construcción de escalera lateral de fundición con barandas de cristal para edificio de departamentos', 870);
insert into proyecto (id, code, description, empresa_id) values (944949, 39483, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 524);
insert into proyecto (id, code, description, empresa_id) values (720995, 49078, 'Construcción de vereda en el lado sur de la calle principal para mejorar la accesibilidad peatonal', 252);
insert into proyecto (id, code, description, empresa_id) values (689219, 22044, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 432);
insert into proyecto (id, code, description, empresa_id) values (64239, 50719, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 575);
insert into proyecto (id, code, description, empresa_id) values (410528, 65799, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 455);
insert into proyecto (id, code, description, empresa_id) values (708631, 95397, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 866);
insert into proyecto (id, code, description, empresa_id) values (55089, 72201, 'Proceso de granallado y pintura en el edificio municipal para renovación estética y protección contra la corrosión', 583);
insert into proyecto (id, code, description, empresa_id) values (261186, 88719, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 16);
insert into proyecto (id, code, description, empresa_id) values (255077, 78749, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 934);
insert into proyecto (id, code, description, empresa_id) values (994354, 10900, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 889);
insert into proyecto (id, code, description, empresa_id) values (847821, 62546, 'Granallado y pintura de fachada en el edificio municipal para revitalización urbana', 944);
insert into proyecto (id, code, description, empresa_id) values (526885, 51257, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 370);
insert into proyecto (id, code, description, empresa_id) values (692835, 45470, 'Instalación de galpón prefabricado en el área norte del terreno para almacenamiento de equipos', 588);
insert into proyecto (id, code, description, empresa_id) values (616153, 93683, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 169);
insert into proyecto (id, code, description, empresa_id) values (34711, 94347, 'Construcción de escalera lateral de fundición con iluminación LED integrada para edificio de oficinas', 235);
insert into proyecto (id, code, description, empresa_id) values (810653, 14320, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 992);
insert into proyecto (id, code, description, empresa_id) values (297895, 49281, 'Instalación de galpón prefabricado en el sector norte del terreno para almacenamiento de productos', 603);
insert into proyecto (id, code, description, empresa_id) values (729661, 69571, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 997);
insert into proyecto (id, code, description, empresa_id) values (667025, 6119, 'Construcción de escalera lateral de fundición con diseño ergonómico para acceso a vivienda unifamiliar', 275);
insert into proyecto (id, code, description, empresa_id) values (10551, 39040, 'Rehabilitación y embellecimiento de vereda en el lado sur de la calle para revitalización del centro urbano', 239);
insert into proyecto (id, code, description, empresa_id) values (390096, 88607, 'Proyecto de granallado para restauración del exterior del edificio municipal', 350);
insert into proyecto (id, code, description, empresa_id) values (267571, 34388, 'Montaje de estructura metálica para galpón en el área norte del complejo industrial', 737);
insert into proyecto (id, code, description, empresa_id) values (600136, 76982, 'Instalación de escalera lateral de fundición para acceso a edificio comercial', 881);
insert into proyecto (id, code, description, empresa_id) values (281871, 19372, 'Montaje de estructura metálica para galpón agrícola en el extremo norte del campo', 423);
insert into proyecto (id, code, description, empresa_id) values (584686, 63873, 'Construcción de escalera lateral de fundición con pasamanos de acero inoxidable para complejo residencial', 351);
insert into proyecto (id, code, description, empresa_id) values (896755, 69307, 'Tratamiento de granallado para eliminar óxido y pintura en el exterior del edificio municipal', 509);
insert into proyecto (id, code, description, empresa_id) values (49338, 93375, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 171);
insert into proyecto (id, code, description, empresa_id) values (781683, 53991, 'Montaje de estructura metálica para galpón en el área norte del terreno para uso industrial.', 64);
insert into proyecto (id, code, description, empresa_id) values (987743, 37612, 'Diseño y construcción de escalera lateral de fundición con acabados de madera para residencia privada', 953);
insert into proyecto (id, code, description, empresa_id) values (162246, 32116, 'Proyecto de granallado para restauración del exterior del edificio municipal', 704);
insert into proyecto (id, code, description, empresa_id) values (267162, 83355, 'Montaje de galpón en el sector norte del terreno para almacenamiento de materiales', 978);
insert into proyecto (id, code, description, empresa_id) values (14324, 68287, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 637);
insert into proyecto (id, code, description, empresa_id) values (129645, 53302, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 171);
insert into proyecto (id, code, description, empresa_id) values (535825, 84509, 'Construcción de escalera lateral de fundición con diseño contemporáneo para complejo residencial', 596);
insert into proyecto (id, code, description, empresa_id) values (76471, 56858, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 959);
insert into proyecto (id, code, description, empresa_id) values (649029, 86903, 'Ampliación y mejoramiento de la vereda en el sector sur de la avenida principal', 337);
insert into proyecto (id, code, description, empresa_id) values (572611, 10484, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 744);
insert into proyecto (id, code, description, empresa_id) values (126343, 76140, 'Rehabilitación y construcción de vereda en el lado sur de la calle para mejorar la movilidad peatonal', 611);
insert into proyecto (id, code, description, empresa_id) values (491993, 79010, 'Proceso de granallado y aplicación de recubrimiento epoxi en el edificio municipal para protección contra la corrosión', 743);
insert into proyecto (id, code, description, empresa_id) values (171347, 85654, 'Mejora y pavimentación de vereda en el lado sur de la calle principal para peatones y ciclistas', 396);
insert into proyecto (id, code, description, empresa_id) values (535972, 54047, 'Diseño y construcción de escalera lateral de fundición con pasamanos de acero galvanizado para edificio comercial', 943);
insert into proyecto (id, code, description, empresa_id) values (642960, 54776, 'Montaje de estructura metálica para galpón en el área norte del terreno industrial', 999);
insert into proyecto (id, code, description, empresa_id) values (726955, 45939, 'Proceso de granallado y aplicación de revestimiento protector en el edificio municipal para prolongar su vida útil', 641);
insert into proyecto (id, code, description, empresa_id) values (38106, 68111, 'Ampliación y embellecimiento de vereda en el lado sur de la avenida principal para promover el turismo', 902);